function handleError(error) {
    console.error('There has been a problem with your fetch operation:', error);
}